[build]
  publish = "docs/.vitepress/dist"
  command = "pnpm run docs:build"

# `/vue/component/` or `/vue/component` => `/vue/component/index.html`
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200