name: CI

on:
  push:
    branches:
      - main
      - next

  pull_request:
    branches:
      - main
      - next

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Lint
        run: pnpm lint --ignore-pattern 'playground'

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14.x, 16.x, 18.x]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Docs build
        run: pnpm run docs:build
      # - name: Typecheck
      #   run: pnpm typecheck

      - name: unit test
        run: pnpm run test
